"""initial

Revision ID: 23c7270b1d79
Revises: 
Create Date: 2026-05-23 17:42:34.680557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23c7270b1d79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quota', sa.BigInteger(), nullable=False),
    sa.Column('price_cents', sa.BigInteger(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False),
    sa.Column('unionid', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('quota_total', sa.BigInteger(), nullable=False),
    sa.Column('quota_used', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('quota_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_logs_user_id'), 'quota_logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('report_month', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('invoice_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_files_project_id'), 'invoice_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoice_files_user_id'), 'invoice_files', ['user_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_project_id'), 'report_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_report_snapshots_share_token'), 'report_snapshots', ['share_token'], unique=True)
    op.create_index(op.f('ix_report_snapshots_user_id'), 'report_snapshots', ['user_id'], unique=False)
    op.create_table('invoice_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('merchant_name', sa.String(length=256), nullable=True),
    sa.Column('tax_no', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('invoice_date', sa.String(length=32), nullable=True),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('category_l1', sa.String(length=128), nullable=True),
    sa.Column('category_l2', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_manual_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['invoice_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_records_file_id'), 'invoice_records', ['file_id'], unique=False)
    op.create_index(op.f('ix_invoice_records_project_id'), 'invoice_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoice_records_user_id'), 'invoice_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_records_user_id'), table_name='invoice_records')
    op.drop_index(op.f('ix_invoice_records_project_id'), table_name='invoice_records')
    op.drop_index(op.f('ix_invoice_records_file_id'), table_name='invoice_records')
    op.drop_table('invoice_records')
    op.drop_index(op.f('ix_report_snapshots_user_id'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_share_token'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_project_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_invoice_files_user_id'), table_name='invoice_files')
    op.drop_index(op.f('ix_invoice_files_project_id'), table_name='invoice_files')
    op.drop_table('invoice_files')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_quota_logs_user_id'), table_name='quota_logs')
    op.drop_table('quota_logs')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    # ### end Alembic commands ###
